image: fedora/latest
packages:
  - elixir
  - gcc-c++
  - openssl-devel
  - zlib-devel
  - gperf
  - cmake
  - tar
sources:
  - https://git.sr.ht/~fnux/elixir-tdlib
tasks:
- build-deps: |
    cd elixir-tdlib
    mix local.hex --force
    mix deps.get
    mix deps.compile
- build: |
    cd elixir-tdlib
    mix compile
- test: |
    cd elixir-tdlib
    mix test
